# Generated by Django 5.0.6 on 2026-09-28 15:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(help_text='Nombre del servicio o web, ej. "GitHub".', max_length=150, verbose_name='Servicio / Sitio web')),
                ('username_or_email', models.CharField(max_length=255, verbose_name='Usuario o correo asociado')),
                ('encrypted_password', models.TextField(help_text='Contraseña cifrada con Fernet (AES-128 + HMAC). Nunca se guarda en texto plano.', verbose_name='Contraseña cifrada')),
                ('strength_score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación de fortaleza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_passwords', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contraseña almacenada',
                'verbose_name_plural': 'Contraseñas almacenadas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'site_name'], name='passwords_s_user_id_2e1f18_idx')],
            },
        ),
    ]
